### ISSUE TITLE
use strict output twice

### ISSUE THREAD

**Issue by thejameskyle** [esperantojs/esperanto#121]
Input:
```js
'use strict';
```

Output:
```js
'use strict';

'use strict';
```

:cry:

**Comment by stefanpenner** [comment]
@thejameskyle I don't see this in my usages of esperanto, do you have steps to reproduce?

**Comment by thejameskyle** [comment]
I just tested it out on http://esperantojs.org/

**Comment by Rich-Harris** [comment]
Yeah, at the moment it doesn't bother checking, the assumption being that if you're writing ES6 modules you're not explicitly using the 'use strict' pragma because you don't have a choice. A good minifier should eliminate the second one, though I don't know off the top of my head if that happens in practice.

My typical workflow involves transpiling with babel then bundling with esperanto. In that case I just blacklist (or don't whitelist) the `useStrict` transform. Though I guess we could detect whether there's already a redundant 'use strict' and skip it if so.

**Comment by stefanpenner** [comment]
i don't see this as a bug

**Comment by eventualbuddha** [comment]
I'm inclined to agree that there's little benefit in checking for this. Closing.

**Comment by Rich-Harris** [comment]
This turned out to be necessary for #141, so you can now pass a `useStrict: false` option and it'll be omitted.
