### ISSUE TITLE
Don't mutate the AST

### ISSUE THREAD

**Issue by bergus** [esperantojs/esperanto#180]
I've noticed that when calling both `toCjs` and `toUmd` on a bundle ends up with a `module.exports` assignment in the UMD factory, and double `'use strict';` directives.
```js
require("esperanto").bundle({
	modules: {
		"test.js": "export default 1;"
	},
	entry: "test.js"
}).then(function(b) {
	b.toCjs().code;
	console.log(b.toUmd({name:"test"}).code);
}, console.error)
```
results in
```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	global.test = factory()
}(this, function () { 'use strict'; // <-- !!!!

	'use strict';

	var test = 1;

	module.exports = test; // <-- !!!!

	return test;

}));
```
This doesn't happen when the line `b.toCjs().code;` is not present. If the method calls are swapped, you will find the UMD wrapper in the cjs code.
Can you please treat the AST as immutable (as far as necessary)? I really would like no to have to call `bundle` multiple times.

**Comment by Rich-Harris** [comment]
Apologies for the slow response. I'm in the process of abandoning this project in favour of [Rollup](https://github.com/rollup/rollup) (see #191), which doesn't have this bug – it'll be fixed in 0.8.0, but my recommendation would be to use Rollup directly. Thanks!

**Comment by bergus** [comment]
Thanks, I've seen already that you're working on rollup, but its description "*This is an early stage project under active development.*" didn't sound as if it were stable yet. You might want to change the tone of that :-)
Also, while the "future-proof better approach" is certainly interesting, I am not sure whether I really need it. It looks like the perfect solution for libraries like Underscore that export lots of tiny, static *helper functions* with clear dependencies, but my module isn't exactly like that.
I still have a rather monolithic API where my module exports one (or actually, multiple similar) classes with lots of prototype methods and static class methods. Many of these need to be called on instances or even on constructor functions respectively (like ES6 `Promise.resolve()`), so I cannot use unbound (`resolve()`) named exports for them. Neither static analysis nor an intelligent bundler can help me with this afaics, so the only reasonable approach I could think of was to export everything, and for those users who need less offer custom builds that [skip](https://github.com/esperantojs/esperanto/wiki/Bundling-multiple-ES6-modules#skip) some submodules.
Can you suggest a better solution for this?
Also, is rollup supposed to be a superset of esperanto? If I don't need/can't use the lazy-bundling (only what is needed) feature, can I expect the output to be the same as with current esperanto?

**Comment by Rich-Harris** [comment]
Ha, you're right! The README is fairly out of date at this point. I need to rewrite it, flesh out the docs, and ideally create a website (I already bought the rollupjs.org domain...)

It's actually pretty stable at this point. I'm using it in a few places without issue, and the Rollup-powered version of Esperanto passes all the tests, and Esperanto has a number of bugs that Rollup doesn't. It's true that there isn't that much benefit to the static analysis Rollup does if you're bundling a library with few or no ES6 dependencies, since it's all your code and is all meant to be included, but at the same time it's harmless (unless a) you're doing something really weird, or b) you find an as-yet-undiscovered bug). The performance difference is negligible as far as I can tell, and the output will be strikingly similar to Esperanto (in most cases slightly slimmer – it's a bit smarter about not renaming things).

The `skip` option is no longer supported – sorry about that. It caused too many problems. You could do custom builds by having multiple entry files:

```js
// my-lib.js
export { foo, bar } from './a';
export { baz } from './b';

// my-lib-foo.js
export { foo } from './a';
```

Then you'd just swap out `entry: 'my-lib.js'` for `entry: 'my-lib-foo.js'` when you invoked Rollup. If you needed more granular control (i.e. it couldn't be done from the entry module) you could use a custom loader, though that's a bit more involved.

Rollup is a subset of Esperanto, because Esperanto does one-to-one transformations whereas Rollup only does bundles (though of course, a bundle of one module *is* a one-to-one transformation...). I'm recommending that people use Babel for one-to-one transformations in future. If it proved necessary, it would certainly be possible to have an `includeKitchenSink: true` option that didn't bother with the tree-shaking. So far I haven't found any reason for it though.

**Comment by bergus** [comment]
Yes, I am doing a few weird things (like having 16 constructors and 4 prototypes as subclasses with slightly different characteristics that all refine the same thing; and *lots* of closures), so I do wonder what kind of static analysis rollup does? You can find the files [here](https://github.com/bergus/F-Promise/tree/master/src) if you're interested.

Also I'm importing some modules only for their side effects, i.e. modifying the shared common prototype object with a set of methods (e.g. `aplus.js`). Those would be the modules that I might want to have skipped, to limit functionality and exclude those methods. I guess this will work if I import them through dedicated entry files.

I'm not sure what a one-to-one transformation is (vs a many-to-one transformation?). I have previously tried to avoid the heavy Babel dependency, as I still code in ES5 and only used ES6 module syntax for structuring my code. I loved how Esperanto keeps the output so close to the input code, and introduces no fluff in the bundling process (Well done!).
