### ISSUE TITLE
Duplicate expressions

### ISSUE THREAD

**Issue by sebmck** [esperantojs/esperanto#51]
```javascript
import { foo } from "foobar";
foo.wow;
```

currently transpiles to

```javascript
'use strict';

var foobar = require('foobar');

foobar.foo.wow;
```

`foobar.foo` is going to be duplicated for every `foo` reference. This will cause unexpected behaviour if `foobar.foo` is a getter etc. It should only be evaluated once.

**Comment by Rich-Harris** [comment]
My understanding is different - isn't `foo` a live binding to whatever the value of foobar's `foo` export is at the time it's referenced, rather than when it's imported? See e.g. [this test case](https://github.com/esperantojs/esperanto/tree/master/test/es6-module-transpiler-tests/input/bindings) borrowed from es6-module-transpiler, or the section beginning 'In order to eliminate the aforementioned two limitations, ECMAScript 6 modules export bindings, not values' in [this article](http://www.2ality.com/2014/09/es6-modules-final.html).

The only way to achieve that in the one-to-one transpilation case is to replace each `foo` reference with `foobar.foo`, as far as I can see. Happy to be corrected though.

**Comment by sebmck** [comment]
It is, but it's not expected to be evaluated on every reference. The duplicate duplicate is more trouble than its worth IMO and it has the ability to introduce nasty bugs. There's no real way to implement ES6 modules 100% without using SystemJS (see #53). I understand the counterargument though so feel free to label this is a wontfix.

**Comment by Rich-Harris** [comment]
> it's not expected to be evaluated on every reference

If not when it's referenced, when? Not sure I follow. Surely any bugs would be the fault of the exporting module doing something crazy with a getter? FWIW things are much simpler inside a bundle, since it's just a reference in the shared scope.

**Comment by eventualbuddha** [comment]
@sebmck My understanding is the same as @Rich-Harris in this case. Is there an example you have that would illustrate this being a problem? Also, a whole-program bundle format can also correctly model the ES6 module spec, live bindings and all. That's what es6-module-transpiler and this project both do with their bundle formats.
