### ISSUE TITLE
AMD Callback dependency with named import shadows local function args

### ISSUE THREAD

**Issue by jschilli** [esperantojs/esperanto#88]
This appears to be another variant of #79 

``` transaction.js

export var transactionTypes = {
...
}

```
``` bar.js

import { transactionTypes as TransactionTypes } from '../models/transaction'
...
function(transaction) {

   var y = TransactionTypes['bletch']
...
```

The transpiled code looks like

```
transaction.types['bletch']
``` 
which is clearly referring to the local function arg not the AMD define arg

This first appeared after upgrading to ember 1.9.1

Thoughts?  can the fix for #85 be extended to cover this?

**Comment by Rich-Harris** [comment]
Thanks, this definitely needs to be fixed. I don't think it'll be quite as straightforward as #85 was, because references that are potentially going to be rewritten need to be deconflicted against their current scope chain, whereas #85 was about deconflicting imports and globals which is easier.

A lazy approach would be to add function arguments to the list of names to deconflict against within the entire module - would work, but would also yield false positives:

```js
import { bar } from './foo';

function a ( foo ) {
  console.log( foo );
}

function b () {
  console.log( bar );
}

a( 'whatever' );
b();
```

Using the simple approach, the `'./foo'` import would unnecessarily change its name to something other than `foo`. That's not the worst thing in the world, so we could resort to that if the more surgical fix proves to be too much of a nuisance.

**Comment by jschilli** [comment]
Agreed - the natural naming of imports certainly makes reading transpiled source more pleasant.

The bug hunting that ensues from shadowing - particularly b/c its at runtime makes it less pleasant.

**Comment by marcins** [comment]
Just ran into this too, de-duping against just function args wouldn't be enough for us. My example:

```js
import * as promiseUtil from 'foo/bar/util/promise';

function fn() {
   var promise = promiseUtil.spinner(...);
}
```

is transpiling to:

```js
var promise = require('foo/bar/util/promise');

function fn() {
   var promise = promise.spinner(...);
}
```

If I've said I want to import "as" something then esperanto should respect that name in the transpiled code, rather than rewriting it.

**Comment by Rich-Harris** [comment]
Apologies for the long delay - both of these issues are now fixed (via other recent issues that were similar)
