### ISSUE TITLE
Combine toX apis

### ISSUE THREAD

**Issue by thejameskyle** [esperantojs/esperanto#90]
Instead of these:

```js
esperanto.toCjs(source, { strict: true });
esperanto.toAmd(source, { strict: true });
esperanto.toUmd(source, { strict: true });
```

It'd make more sense to have an api like:

```js
esperanto.transform(source, { type: 'cjs', strict: true });
esperanto.transform(source, { type: 'amd', strict: true });
esperanto.transform(source, { type: 'umd', strict: true });
```

Which avoids stuff like this:

https://github.com/Attamusc/gulp-esperanto/blob/master/index.js#L7-L10

**Comment by Rich-Harris** [comment]
+1, now that I think about it. Same thing happens with gobble-esperanto: https://github.com/gobblejs/gobble-esperanto/blob/master/index.js#L5-L12

**Comment by thejameskyle** [comment]
ping, just trying to close out old issues right now

**Comment by Rich-Harris** [comment]
Yep, this is still planned - haven't had much of a chance to work on Esperanto in a while (in part because I've been working on [Rollup](https://github.com/rollup/rollup) instead, which is a sort of sequel/potential replacement for Esperanto - you'll be pleased to know it has an API that was informed by this issue), but one day. If anyone out there has the energy to do a PR I would gladly accept it!

**Comment by Rich-Harris** [comment]
Closing as wontfix, per #191. Rollup uses this form (`bundle.generate({format:'cjs',...})`), and for non-bundling purposes I'm recommending that people use Babel instead.
