### ISSUE TITLE
Reversed Load Order

### ISSUE THREAD

**Issue by ef4** [esperantojs/esperanto#92]
When importing modules for side-effect and exporting AMD, the dependencies get loaded in the wrong order:

````js
import "foo";
import "bar";
````

Gets translated to:

````js
define(['bar', 'foo'], function () {
  'use strict';
});
````

I was expecting `['foo', 'bar']` instead, which would evaluate the modules in the original order.

**Comment by Rich-Harris** [comment]
Ah, this would be a side-effect of [this module](https://github.com/esperantojs/esperanto/blob/master/src/utils/reorderImports.js), which ensures that empty imports are at the end so that they don't need to be represented as function arguments.

We could fix this particular case by ensuring that empty imports stay in the same order, though it might still cause problems if you had...

```js
import 'a';
import 'b';
import sideEffectyModule from 'c';
```

...and needed the modules to load in a, b, c order (they would load in c, a, b). So the only way to truly prevent that scenario arising would be to not reorder imports at all, even though it would result in something like this:

```js
define(['a', 'b', 'c'], function (__a__, __b__, sideEffectyModule) {
  // ...
});
```

Any thoughts?

**Comment by ef4** [comment]
Yeah, I can see we're somewhat constrained by the AMD format. What about something like this?

````js
define(['a', 'b', 'c'], function() {
  (function(sideEffectyModule){
    // ...
  })(arguments[2]);
});

**Comment by ef4** [comment]
Your suggestion with underscores is also fine with me, I was just trying to find ways to avoid sticking extra vars in scope.
